version: 1

discord:
  prefix: ir!
  globalratelimit:
    burst: 2
    restoration: 10

permission:
  user:
  - +rs.etc.*
  - +rs.chat.*
  admin:
  - +rs.guild.*
  - +rs.etc.*
  - rs.chat.*

logging:
  enabled: true
  level: 1

metrics:
  enabled: true
  address: ":9000"
